# hyperparameters

seed: 0

env:
  type: "dmcontrol"  # options: dmcontrol, brax
  expert:
    name: "pendulum_swingup"  #  "cartpole_balance" 
  imitator:
    # name: "cartpole_balance"
    # physics: 
    #   - key: "body_mass_cart"
    #     value: 1.0
    #   - key: "body_mass_pole_1"
    #     value: 1.0
    #   - key: "geom_size_cart"
    #     value: 1.0
    #   - key: "geom_size_pole_1"
    #     value: 1.0

    name: "pendulum_swingup"
    physics: 
      - key: "body_mass_pole"
        value: 1.0
    
    # name: "cheetah_run"
    # physics: 
    #   - key: "body_mass_torso"
    #     value: 3.0
    #   - key: "jnt_stiffness_bfoot"
    #     value: 1.0
    #   - key: "jnt_stiffness_ffoot"
    #     value: 1.0

mpc:
  normalizer:
    state: "standard_norm"  # option "standard_norm" or "identity"
    action: "identity" 
  horizon: 5
  history: 5   # need value >= 1
  model:
    cost:
      weights:
        action: -20.0
        state: 3.0
        terminal: 1.0
      mlp:
        num_layers: 3
        num_hidden_units: 128
        fout: 10
    dynamics:
      use: "mlp"
      mlp:
        num_layers: 4
        num_hidden_units: 200
      lstm:
        lstm_features: 64
        num_layers: 3
        num_hidden_units: 128
    critic:
      use: "lstm"
      algo: "js_gan"  # w_gan
      lstm:
        lstm_features: 64
        num_layers: 2
        num_hidden_units: 128
    expert:
      load_id: "0"
  train:
    num_epochs: 20
    print_after_n_epochs: 1
    num_trajectories: 5
    trajectory_len: 500
    cost:
      num_updates: 2
      batch_size: 64
      learning_rate: 1.0e-5
      polyak_factor: 0.0
      no_grads: ["dynamics_params", "critic_params", "expert_params"]
    dynamics:
      num_episodes: 1
      max_interactions_per_episode: 200
      replay_buffer_size: 1000
      num_updates: 1
      batch_size: 64
      learning_rate: 1.0e-4
      discount_factor: 0.0
      teacher_forcing_factor: 0.7
      no_grads: ["mpc_weights", "cost_params", "critic_params", "expert_params"]
    critic:
      num_updates: 5
      batch_size: 64
      learning_rate: 1.0e-4
      entropy_rate: 0.0
      grad_penalty_rate: 10.0
      no_grads: ["mpc_weights", "cost_params", "dynamics_params", "expert_params"]
  evaluate:
    max_interactions: 1000
    num_runs_for_avg: 1
    save_video: True


expert_prediction:
  model:
    use: "lstm"
    mlp:
      num_layers: 3
      num_hidden_units: 128
    lstm:
      lstm_features: 128
      num_layers: 3
      num_hidden_units: 128
  train:
    num_epochs: 10
    batch_size: 64
    seqlen: 10
    learning_rate: 1.0e-4
    discount_factor: 0.9
    teacher_forcing_factor: 0.7
    print_step: 10
