# hyperparameters 

seed: 0

env:
  type: "dmcontrol"  # options: dmcontrol, brax
  expert:
    name: "cartpole-balance"
  imitator:
    name: "cartpole-balance"


mpc:
  horizon: 10
  model:
    cost:
      mlp:
        num_layers: 3
        num_hidden_units: 128
    dynamics:
      mlp:
        num_layers: 3
        num_hidden_units: 128


expert_prediction:
  model:
    mlp:
      num_layers: 2
      num_hidden_units: 128
      state:
        num_layers: 2
        num_hidden_units: 128
      action:
        num_layers: 2
        num_hidden_units: 128
  train:
    num_epochs: 10
    batch_size: 64
    learning_rate: 1e-4
    discount_factor: 0.8


train:
  num_trajectories: 50
  num_epochs: 10
  batch_size: 64
  learning_rate: 1e-4
