# hyperparameters 

seed: 0

env:
  type: "dmcontrol"  # options: dmcontrol, brax
  expert:
    name: "cartpole_balance"
  imitator:
    name: "cartpole_balance"


mpc:
  horizon: 10
  model:
    cost:
      mlp:
        num_layers: 3
        num_hidden_units: 128
    dynamics:
      mlp:
        num_layers: 3
        num_hidden_units: 128


expert_prediction:
  model:
    mlp:
      num_layers: 3
      num_hidden_units: 128
      use: false
    lstm:
      lstm_features: 128
      num_layers: 3
      num_hidden_units: 128
      use: true

  train:
    num_epochs: 10
    batch_size: 64
    seqlen: 10
    learning_rate: 1.0e-4
    discount_factor: 0.9
    teacher_forcing_factor: 0.7
    print_step: 10


train:
  num_trajectories: 50
  num_epochs: 10
  batch_size: 64
  learning_rate: 1.0e-4
