# hyperparameters 

seed: 0

env:
  type: "dmcontrol"  # options: dmcontrol, brax
  expert:
    name: "cartpole_balance"
  imitator:
    name: "cartpole_balance"


mpc:
  horizon: 10
  model:
    cost:
      weights:
        action: 1.0
        state: 3.0
        terminal: 0.0
      mlp:
        num_layers: 3
        num_hidden_units: 128
        fout: 10
    dynamics:
      mlp:
        num_layers: 3
        num_hidden_units: 128


expert_prediction:
  model:
    use: "lstm"
    mlp:
      num_layers: 3
      num_hidden_units: 128
    lstm:
      lstm_features: 128
      num_layers: 3
      num_hidden_units: 128
  train:
    num_epochs: 10
    batch_size: 64
    seqlen: 10
    learning_rate: 1.0e-4
    discount_factor: 0.9
    teacher_forcing_factor: 0.7
    print_step: 10
  load:
    id: "1"


train:
  num_trajectories: 50
  num_epochs: 10
  batch_size: 64
  learning_rate: 1.0e-4
  print_step: 10
